import React from "react"
import ProgressSection from "./progress_section"

const SkillGraphs = () => (
  <div style={{marginTop: `15px`}}>
    <ProgressSection
      percent="100"
      color="#F47064"
      text="Level3"
      title="Ruby"
    ></ProgressSection>
    <ProgressSection
      percent="67"
      color="#018E04"
      text="Level2"
      title="JS"
    ></ProgressSection>
    <ProgressSection
      percent="67"
      color="#018E04"
      text="Level2"
      title="PHP"
    ></ProgressSection>
    <ProgressSection
      percent="33"
      color="#2269EA"
      text="Level1"
      title="Python"
    ></ProgressSection>
    <ProgressSection
      percent="33"
      color="#2269EA"
      text="Level1"
      title="C++"
    ></ProgressSection>
    <ProgressSection
      percent="100"
      color="#F47064"
      text="Level3"
      title="Rails"
    ></ProgressSection>
    <ProgressSection
      percent="100"
      color="#F47064"
      text="Level3"
      title="Nuxt.js"
    ></ProgressSection>
    <ProgressSection
      percent="100"
      color="#F47064"
      text="Level3"
      title="Vue.js"
    ></ProgressSection>
    <ProgressSection
      percent="67"
      color="#018E04"
      text="Level2"
      title="WordPress"
    ></ProgressSection>
    <ProgressSection
      percent="33"
      color="#2269EA"
      text="Level1"
      title="Laravel"
    ></ProgressSection>
    <ProgressSection
      percent="33"
      color="#2269EA"
      text="Level1"
      title="Gatsby.js"
    ></ProgressSection>
    <ProgressSection
      percent="33"
      color="#2269EA"
      text="Level1"
      title="React.js"
    ></ProgressSection>
    <ProgressSection
      percent="100"
      color="#F47064"
      text="Level3"
      title="MySQL"
    ></ProgressSection>
    <ProgressSection
      percent="100"
      color="#F47064"
      text="Level3"
      title="HTML&CSS"
    ></ProgressSection>
    <ProgressSection
      percent="100"
      color="#F47064"
      text="Level3"
      title="VPS(CentOS)"
    ></ProgressSection>
    <ProgressSection
      percent="67"
      color="#018E04"
      text="Level2"
      title="Nginx"
    ></ProgressSection>
    <ProgressSection
      percent="67"
      color="#018E04"
      text="Level2"
      title="Apache"
    ></ProgressSection>
    <ProgressSection
      percent="67"
      color="#018E04"
      text="Level2"
      title="AWS"
    ></ProgressSection>
  </div>
)



export default SkillGraphs
